name: GroupProject
on: 
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
jobs:
  BuildAndTestUbuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
    
      - name: Build and Run Library API
        shell: bash
        run: docker compose up -d

      - name: Compile Linux Python Binary From Source
        shell: bash
        run: |
          cd UserInterface
          python -m pip install -r requirements.txt
          pyinstaller --onefile client.py
          ls dist

      - name: Compile Windows Python Binary From Source
        shell: bash
        run: |
          sudo apt install wine -y
          cd UserInterface
          wine pyinstaller --onefile client.py
          ls dist
      
      - name: Make Linux Binary Available
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: ./UserInterface/dist/client

      - name: Make Windows Binary Available
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: ./UserInterface/dist/client
