name: GroupProject
on: 
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Run Library API
        shell: bash
        run: docker compose up -d
